# Join and preprocess multiple time series data

## Load data

In [1]:
path = '../../data/data_FRED/CORESTICKM159SFRBATL.csv'

In [2]:
import pandas as pd

pdf = pd.read_csv(filepath_or_buffer=path, index_col='observation_date')

In [3]:
pdf.plot(title='FRED Data - first PDF (Inflation)')

## Parse dates to join time series

In [4]:
path = '../../data/data_FRED/CORESTICKM159SFRBATL.csv'
pdf1 = pd.read_csv(filepath_or_buffer=path, 
                   index_col='observation_date',
                   parse_dates=True)

pdf1

                  CORESTICKM159SFRBATL
observation_date
1968-01-01                    3.651861
1968-02-01                    3.673819
...                                ...
2026-03-01                    2.929321
2026-04-01                    3.038932

[700 rows x 1 columns]

In [5]:
path = '../../data/data_FRED/MORTGAGE30US.csv'
pdf2 = pd.read_csv(filepath_or_buffer=path, 
                   index_col='observation_date',
                   parse_dates=True)

pdf2

                  MORTGAGE30US
observation_date
1971-04-02                7.33
1971-04-09                7.31
...                        ...
2026-05-07                6.37
2026-05-14                6.36

[2877 rows x 1 columns]

In [6]:
pdf1.index

DatetimeIndex(['1968-01-01', '1968-02-01', '1968-03-01', '1968-04-01',
               '1968-05-01', '1968-06-01', '1968-07-01', '1968-08-01',
               '1968-09-01', '1968-10-01',
               ...
               '2025-07-01', '2025-08-01', '2025-09-01', '2025-10-01',
               '2025-11-01', '2025-12-01', '2026-01-01', '2026-02-01',
               '2026-03-01', '2026-04-01'],
              dtype='datetime64[ns]', name='observation_date', length=700, freq=None)

In [7]:
pdf_join = pd.concat([pdf1, pdf2], axis=1, )
pdf_join.tail(50).style

In [8]:
pdf_join.plot(title='FRED Data - Outer Join')

## Inner join vs outer join

In [9]:
pdf_join_inner = pd.concat([pdf1, pdf2], axis=1, join='inner')
pdf_join_inner.tail(10).style

In [10]:
pdf_join_inner.plot(title="FRED Data - Inner Join")

## Interpolate missing values

In [11]:
pdf_join = pd.concat([pdf1, pdf2], axis=1, join='outer')
pdf_join.tail(20).style

In [12]:
pdf_join_interpl = pdf_join.interpolate(method='linear')
pdf_join_interpl.tail(20).style

In [13]:
pdf_join_interpl.plot(title = 'FRED Data - Linear Interpolated')

## Iterate for seamless loading of multiple datasets

In [14]:
paths = [
    '../../data/data_FRED/CORESTICKM159SFRBATL.csv',
    '../../data/data_FRED/MORTGAGE30US.csv',
    '../../data/data_FRED/FEDFUNDS.csv',
    '../../data/data_FRED/T10YIE.csv',
    '../../data/data_FRED/UNRATE.csv'
]

pdfs = []
for path in paths:
    pdf_i = pd.read_csv(path, index_col=0, parse_dates=True)
    pdfs.append(pdf_i)
pdfs

[                  CORESTICKM159SFRBATL
 observation_date
 1968-01-01                    3.651861
 1968-02-01                    3.673819
 ...                                ...
 2026-03-01                    2.929321
 2026-04-01                    3.038932

 [700 rows x 1 columns],
                   MORTGAGE30US
 observation_date
 1971-04-02                7.33
 1971-04-09                7.31
 ...                        ...
 2026-05-07                6.37
 2026-05-14                6.36

 [2877 rows x 1 columns],
                   FEDFUNDS
 observation_date
 1954-07-01            0.80
 1954-08-01            1.22
 ...                    ...
 2026-03-01            3.64
 2026-04-01            3.64

 [862 rows x 1 columns],
                   T10YIE
 observation_date
 2021-05-17          2.54
 2021-05-18          2.52
 ...                  ...
 2026-05-14          2.47
 2026-05-15          2.49

 [1305 rows x 1 columns],
                   UNRATE
 observation_date
 1948-01-01           3.4
 1948-02-01           3.8
 ...                  ...
 2026-03-01           4.3
 2026-04-01           4.3

 [940 rows x 1 columns]]

In [15]:
pdfs_concat = pd.concat(pdfs, axis=1, join='outer')
pdfs_concat.tail(20).style

In [16]:
pdfs_interpl = pdfs_concat.interpolate(method='linear')
pdfs_interpl.tail(20).style

In [17]:
pdfs_interpl.plot(title = 'FRED Data - multiple datasets, liner interplotated')

## Export data

In [18]:
pdfs_interpl.index.name = 'date'
pdfs_interpl

            CORESTICKM159SFRBATL  MORTGAGE30US  FEDFUNDS  T10YIE  UNRATE
date
1948-01-01                   NaN           NaN       NaN     NaN     3.4
1948-02-01                   NaN           NaN       NaN     NaN     3.8
...                          ...           ...       ...     ...     ...
2026-05-14              3.038932          6.36      3.64    2.47     4.3
2026-05-15              3.038932          6.36      3.64    2.49     4.3

[4739 rows x 5 columns]

In [19]:
pdfs_interpl_renamed = pdfs_interpl.rename(columns={
    'CORESTICKM159SFRBATL': 'CPI',
    'MORTGAGE30US': 'MR',
    'FEDFUNDS': 'FFR',
    'T10YIE': 'INF10',
    'UNRATE': 'UNRT'
})
pdfs_interpl_renamed

                 CPI    MR   FFR  INF10  UNRT
date
1948-01-01       NaN   NaN   NaN    NaN   3.4
1948-02-01       NaN   NaN   NaN    NaN   3.8
...              ...   ...   ...    ...   ...
2026-05-14  3.038932  6.36  3.64   2.47   4.3
2026-05-15  3.038932  6.36  3.64   2.49   4.3

[4739 rows x 5 columns]

In [20]:
pdfs_interpl_renamed.plot(title = 'FRED Data - PDFS Liner Interpl renamed')

In [21]:
pdfs_interpl_renamed.to_csv('../../data/data_FRED/FRED_joined.csv')
pdfs_interpl_renamed.to_parquet('../../data/data_FRED/FRED_joined.parquet')

In [22]:
pd.read_parquet('../../data/data_FRED/FRED_joined.parquet')

                 CPI    MR   FFR  INF10  UNRT
date
1948-01-01       NaN   NaN   NaN    NaN   3.4
1948-02-01       NaN   NaN   NaN    NaN   3.8
...              ...   ...   ...    ...   ...
2026-05-14  3.038932  6.36  3.64   2.47   4.3
2026-05-15  3.038932  6.36  3.64   2.49   4.3

[4739 rows x 5 columns]

In [ ]:
# pip install openpyxl ## in Terminal Window
# import openpyxl

pdfs_interpl_renamed.to_excel('../../data/data_FRED/FRED_joined.xlsx')

ModuleNotFoundError: No module named 'openpyxl'